version: '3.1'
#
services:

  base: 
    build: bacula-base/
    image: wethinksolutionsbr/bacula-base:latest
#    
  db:
    build: bacula-catalog/
    image: wethinksolutionsbr/bacula-catalog:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: bacula
      POSTGRES_USER: bacula
      POSTGRES_DB: bacula
    # volumes:
    #   - pgdata:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
#
  smtp:
    image: wethinksolutionsbr/bacula-smtp:latest
    restart: unless-stopped
    environment:
      MAIL_USER: email@dominio.com.br
      MAIL_PASS: Senha
      MAIL_HOST: smtp.dominio.com.br
      MAIL_PORT: 587
    ports:
      - 25:25
#
  bacula-dir:
    build: bacula-dir/
    image: wethinksolutionsbr/bacula-director:latest
    restart: unless-stopped
    volumes:
      - ./etc:/opt/bacula/etc:ro
      - ./home:/home:rw
      - ./working:/opt/bacula/working:rw
    depends_on: 
      - db      
      - smtp
    ports:
      - 9101:9101
#
  bacula-sd:
    build: bacula-sd/
    image: wethinksolutionsbr/bacula-storage:latest
    restart: unless-stopped
    depends_on:
      - bacula-dir
      - db
      - smtp
    volumes:
      - ./etc:/opt/bacula/etc:ro
      - ./home:/home:rw
      - ./working:/opt/bacula/working:rw      
    ports:
      - 9103:9103
#
  bacula-fd:
    build: bacula-fd/
    image: wethinksolutionsbr/bacula-client:latest
    restart: unless-stopped
    depends_on:
      - bacula-sd
      - bacula-dir
      - smtp
    volumes:
      - ./etc:/opt/bacula/etc:ro
      - ./home:/home:rw
      - ./working:/opt/bacula/working:rw
    ports:
      - 9102:9102
#
  baculum:
    build: baculum/
    image: wethinksolutionsbr/baculum:latest
    restart: unless-stopped
    depends_on: 
      - db
      - bacula-dir
      - smtp
    volumes:
      - ./etc/bconsole.conf:/opt/bacula/etc/bconsole.conf:ro
      - ./etc/baculum:/etc/baculum:rw
    ports:
      - 9095:9095
      - 9096:9096
# 
#volumes: 
#  pgdata:
